<?php

namespace App\Http\Controllers\Help;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ADM_Helper extends Controller
{
    //
    static $categories = [
        'social_media',
        'content_creation',
        'digital_marketing',
        'influencer_marketing',
        'brand_strategy',
        'paid_advertising',
        'seo_optimization',
        'email_marketing',
        'social_analytics',
        'affiliate_marketing',
        'video_marketing',
        'personal_branding',
        'community_management',
        'campaign_management',
        'creative_strategy',
        'social_trends',
        'brand_awareness',
        'customer_engagement',
        'viral_content',
        'social_growth',
    ];
    
    static $states_list = [
        ['id' => 1,'state' => 'Abia'],
        ['id' => 2,'state' => 'Adamawa'],
        ['id' => 3,'state' => 'Akwa Ibom'],
        ['id' => 4,'state' => 'Anambra'],
        ['id' => 5,'state' => 'Bauchi'],
        ['id' => 6,'state' => 'Bayelsa'],
        ['id' => 7,'state' => 'Benue'],
        ['id' => 8,'state' => 'Borno'],
        ['id' => 9,'state' => 'Cross River'],
        ['id' => 10,'state' => 'Delta'],
        ['id' => 11,'state' => 'Ebonyi'],
        ['id' => 12,'state' => 'Enugu'],
        ['id' => 13,'state' => 'Edo'],
        ['id' => 14,'state' => 'Ekiti'],
        ['id' => 15,'state' => 'Gombe'],
        ['id' => 16,'state' => 'Imo'],
        ['id' => 17,'state' => 'Jigawa'],
        ['id' => 18,'state' => 'Kaduna'],
        ['id' => 19,'state' => 'Kano'],
        ['id' => 20,'state' => 'Kastina'],
        ['id' => 21,'state' => 'Kebbi'],
        ['id' => 22,'state' => 'Kogi'],
        ['id' => 23,'state' => 'Kwara'],
        ['id' => 24,'state' => 'Lagos'],
        ['id' => 25,'state' => 'Nasarawa'],
        ['id' => 26,'state' => 'Niger'],
        ['id' => 27,'state' => 'Ogun'],
        ['id' => 28,'state' => 'Ondo'],
        ['id' => 29,'state' => 'Osun'],
        ['id' => 30,'state' => 'Oyo'],
        ['id' => 31,'state' => 'Plateau'],
        ['id' => 32,'state' => 'Rivers'],
        ['id' => 33,'state' => 'Sokoto'],
        ['id' => 34,'state' => 'Taraba'],
        ['id' => 35,'state' => 'Yobe'],
        ['id' => 36,'state' => 'Zamfara'],
        ['id' => 37,'state' => 'Abuja(FCT]']
      ];

      static $lga_NG = [
        ['id' => '1','lga' => 'Aba North','state_id' => '1'],
        ['id' => '2','lga' => 'Aba South','state_id' => '1'],
        ['id' => '3','lga' => 'Arochukwu','state_id' => '1'],
        ['id' => '4','lga' => 'Bende','state_id' => '1'],
        ['id' => '5','lga' => 'Ikwuano','state_id' => '1'],
        ['id' => '6','lga' => 'Isiala Ngwa North','state_id' => '1'],
        ['id' => '7','lga' => 'Isiala Ngwa South','state_id' => '1'],
        ['id' => '8','lga' => 'Isuikwuato','state_id' => '1'],
        ['id' => '9','lga' => 'Obi Ngwa','state_id' => '1'],
        ['id' => '10','lga' => 'Ohafia','state_id' => '1'],
        ['id' => '11','lga' => 'Osisioma','state_id' => '1'],
        ['id' => '12','lga' => 'Ugwunagbo','state_id' => '1'],
        ['id' => '13','lga' => 'Ukwa East','state_id' => '1'],
        ['id' => '14','lga' => 'Ukwa West','state_id' => '1'],
        ['id' => '15','lga' => 'Umu Nneochi','state_id' => '1'],
        ['id' => '16','lga' => 'Umuahia North','state_id' => '1'],
        ['id' => '17','lga' => 'Umuahia South','state_id' => '1'],
        ['id' => '18','lga' => 'Demsa','state_id' => '2'],
        ['id' => '19','lga' => 'Fufure','state_id' => '2'],
        ['id' => '20','lga' => 'Ganye','state_id' => '2'],
        ['id' => '21','lga' => 'Gayuk','state_id' => '2'],
        ['id' => '22','lga' => 'Gombi','state_id' => '2'],
        ['id' => '23','lga' => 'Grie','state_id' => '2'],
        ['id' => '24','lga' => 'Hong','state_id' => '2'],
        ['id' => '25','lga' => 'Jada','state_id' => '2'],
        ['id' => '26','lga' => 'Lamurde','state_id' => '2'],
        ['id' => '27','lga' => 'Madagali','state_id' => '2'],
        ['id' => '28','lga' => 'Maiha','state_id' => '2'],
        ['id' => '29','lga' => 'Mayo Belwa','state_id' => '2'],
        ['id' => '30','lga' => 'Michika','state_id' => '2'],
        ['id' => '31','lga' => 'Mubi North','state_id' => '2'],
        ['id' => '32','lga' => 'Mubi South','state_id' => '2'],
        ['id' => '33','lga' => 'Numan','state_id' => '2'],
        ['id' => '34','lga' => 'Shelleng','state_id' => '2'],
        ['id' => '35','lga' => 'Song','state_id' => '2'],
        ['id' => '36','lga' => 'Toungo','state_id' => '2'],
        ['id' => '37','lga' => 'Yola North','state_id' => '2'],
        ['id' => '38','lga' => 'Yola South','state_id' => '2'],
        ['id' => '39','lga' => 'Abak','state_id' => '3'],
        ['id' => '40','lga' => 'Eastern Obolo','state_id' => '3'],
        ['id' => '41','lga' => 'Eket','state_id' => '3'],
        ['id' => '42','lga' => 'Esit Eket','state_id' => '3'],
        ['id' => '43','lga' => 'Essien Udim','state_id' => '3'],
        ['id' => '44','lga' => 'Etim Ekpo','state_id' => '3'],
        ['id' => '45','lga' => 'Etinan','state_id' => '3'],
        ['id' => '46','lga' => 'Ibeno','state_id' => '3'],
        ['id' => '47','lga' => 'Ibesikpo Asutan','state_id' => '3'],
        ['id' => '48','lga' => 'Ibiono-Ibom','state_id' => '3'],
        ['id' => '49','lga' => 'Ika','state_id' => '3'],
        ['id' => '50','lga' => 'Ikono','state_id' => '3'],
        ['id' => '51','lga' => 'Ikot Abasi','state_id' => '3'],
        ['id' => '52','lga' => 'Ikot Ekpene','state_id' => '3'],
        ['id' => '53','lga' => 'Ini','state_id' => '3'],
        ['id' => '54','lga' => 'Itu','state_id' => '3'],
        ['id' => '55','lga' => 'Mbo','state_id' => '3'],
        ['id' => '56','lga' => 'Mkpat-Enin','state_id' => '3'],
        ['id' => '57','lga' => 'Nsit-Atai','state_id' => '3'],
        ['id' => '58','lga' => 'Nsit-Ibom','state_id' => '3'],
        ['id' => '59','lga' => 'Nsit-Ubium','state_id' => '3'],
        ['id' => '60','lga' => 'Obot Akara','state_id' => '3'],
        ['id' => '61','lga' => 'Okobo','state_id' => '3'],
        ['id' => '62','lga' => 'Onna','state_id' => '3'],
        ['id' => '63','lga' => 'Oron','state_id' => '3'],
        ['id' => '64','lga' => 'Oruk Anam','state_id' => '3'],
        ['id' => '65','lga' => 'Udung-Uko','state_id' => '3'],
        ['id' => '66','lga' => 'Ukanafun','state_id' => '3'],
        ['id' => '67','lga' => 'Uruan','state_id' => '3'],
        ['id' => '68','lga' => 'Urue-Offong/Oruko','state_id' => '3'],
        ['id' => '69','lga' => 'Uyo','state_id' => '3'],
        ['id' => '70','lga' => 'Aguata','state_id' => '4'],
        ['id' => '71','lga' => 'Anambra East','state_id' => '4'],
        ['id' => '72','lga' => 'Anambra West','state_id' => '4'],
        ['id' => '73','lga' => 'Anaocha','state_id' => '4'],
        ['id' => '74','lga' => 'Awka North','state_id' => '4'],
        ['id' => '75','lga' => 'Awka South','state_id' => '4'],
        ['id' => '76','lga' => 'Ayamelum','state_id' => '4'],
        ['id' => '77','lga' => 'Dunukofia','state_id' => '4'],
        ['id' => '78','lga' => 'Ekwusigo','state_id' => '4'],
        ['id' => '79','lga' => 'Idemili North','state_id' => '4'],
        ['id' => '80','lga' => 'Idemili South','state_id' => '4'],
        ['id' => '81','lga' => 'Ihiala','state_id' => '4'],
        ['id' => '82','lga' => 'Njikoka','state_id' => '4'],
        ['id' => '83','lga' => 'Nnewi North','state_id' => '4'],
        ['id' => '84','lga' => 'Nnewi South','state_id' => '4'],
        ['id' => '85','lga' => 'Ogbaru','state_id' => '4'],
        ['id' => '86','lga' => 'Onitsha North','state_id' => '4'],
        ['id' => '87','lga' => 'Onitsha South','state_id' => '4'],
        ['id' => '88','lga' => 'Orumba North','state_id' => '4'],
        ['id' => '89','lga' => 'Orumba South','state_id' => '4'],
        ['id' => '90','lga' => 'Oyi','state_id' => '4'],
        ['id' => '91','lga' => 'Alkaleri','state_id' => '5'],
        ['id' => '92','lga' => 'Bauchi','state_id' => '5'],
        ['id' => '93','lga' => 'Bogoro','state_id' => '5'],
        ['id' => '94','lga' => 'Damban','state_id' => '5'],
        ['id' => '95','lga' => 'Darazo','state_id' => '5'],
        ['id' => '96','lga' => 'Dass','state_id' => '5'],
        ['id' => '97','lga' => 'Gamawa','state_id' => '5'],
        ['id' => '98','lga' => 'Ganjuwa','state_id' => '5'],
        ['id' => '99','lga' => 'Giade','state_id' => '5'],
        ['id' => '100','lga' => 'Itas/Gadau','state_id' => '5'],
        ['id' => '101','lga' => 'Jama\'are','state_id' => '5'],
        ['id' => '102','lga' => 'Katagum','state_id' => '5'],
        ['id' => '103','lga' => 'Kirfi','state_id' => '5'],
        ['id' => '104','lga' => 'Misau','state_id' => '5'],
        ['id' => '105','lga' => 'Ningi','state_id' => '5'],
        ['id' => '106','lga' => 'Shira','state_id' => '5'],
        ['id' => '107','lga' => 'Tafawa Balewa','state_id' => '5'],
        ['id' => '108','lga' => 'Toro','state_id' => '5'],
        ['id' => '109','lga' => 'Warji','state_id' => '5'],
        ['id' => '110','lga' => 'Zaki','state_id' => '5'],
        ['id' => '111','lga' => 'Brass','state_id' => '6'],
        ['id' => '112','lga' => 'Ekeremor','state_id' => '6'],
        ['id' => '113','lga' => 'Kolokuma/Opokuma','state_id' => '6'],
        ['id' => '114','lga' => 'Nembe','state_id' => '6'],
        ['id' => '115','lga' => 'Ogbia','state_id' => '6'],
        ['id' => '116','lga' => 'Sagbama','state_id' => '6'],
        ['id' => '117','lga' => 'Southern Ijaw','state_id' => '6'],
        ['id' => '118','lga' => 'Yenagoa','state_id' => '6'],
        ['id' => '119','lga' => 'Ado','state_id' => '7'],
        ['id' => '120','lga' => 'Agatu','state_id' => '7'],
        ['id' => '121','lga' => 'Apa','state_id' => '7'],
        ['id' => '122','lga' => 'Buruku','state_id' => '7'],
        ['id' => '123','lga' => 'Gboko','state_id' => '7'],
        ['id' => '124','lga' => 'Guma','state_id' => '7'],
        ['id' => '125','lga' => 'Gwer East','state_id' => '7'],
        ['id' => '126','lga' => 'Gwer West','state_id' => '7'],
        ['id' => '127','lga' => 'Katsina-Ala','state_id' => '7'],
        ['id' => '128','lga' => 'Konshisha','state_id' => '7'],
        ['id' => '129','lga' => 'Kwande','state_id' => '7'],
        ['id' => '130','lga' => 'Logo','state_id' => '7'],
        ['id' => '131','lga' => 'Makurdi','state_id' => '7'],
        ['id' => '132','lga' => 'Obi','state_id' => '7'],
        ['id' => '133','lga' => 'Ogbadibo','state_id' => '7'],
        ['id' => '134','lga' => 'Ohimini','state_id' => '7'],
        ['id' => '135','lga' => 'Oju','state_id' => '7'],
        ['id' => '136','lga' => 'Okpokwu','state_id' => '7'],
        ['id' => '137','lga' => 'Oturkpo','state_id' => '7'],
        ['id' => '138','lga' => 'Tarka','state_id' => '7'],
        ['id' => '139','lga' => 'Ukum','state_id' => '7'],
        ['id' => '140','lga' => 'Ushongo','state_id' => '7'],
        ['id' => '141','lga' => 'Vandeikya','state_id' => '7'],
        ['id' => '142','lga' => 'Abadam','state_id' => '8'],
        ['id' => '143','lga' => 'Askira/Uba','state_id' => '8'],
        ['id' => '144','lga' => 'Bama','state_id' => '8'],
        ['id' => '145','lga' => 'Bayo','state_id' => '8'],
        ['id' => '146','lga' => 'Biu','state_id' => '8'],
        ['id' => '147','lga' => 'Chibok','state_id' => '8'],
        ['id' => '148','lga' => 'Damboa','state_id' => '8'],
        ['id' => '149','lga' => 'Dikwa','state_id' => '8'],
        ['id' => '150','lga' => 'Gubio','state_id' => '8'],
        ['id' => '151','lga' => 'Guzamala','state_id' => '8'],
        ['id' => '152','lga' => 'Gwoza','state_id' => '8'],
        ['id' => '153','lga' => 'Hawul','state_id' => '8'],
        ['id' => '154','lga' => 'Jere','state_id' => '8'],
        ['id' => '155','lga' => 'Kaga','state_id' => '8'],
        ['id' => '156','lga' => 'Kala/Balge','state_id' => '8'],
        ['id' => '157','lga' => 'Konduga','state_id' => '8'],
        ['id' => '158','lga' => 'Kukawa','state_id' => '8'],
        ['id' => '159','lga' => 'Kwaya Kusar','state_id' => '8'],
        ['id' => '160','lga' => 'Mafa','state_id' => '8'],
        ['id' => '161','lga' => 'Magumeri','state_id' => '8'],
        ['id' => '162','lga' => 'Maiduguri','state_id' => '8'],
        ['id' => '163','lga' => 'Marte','state_id' => '8'],
        ['id' => '164','lga' => 'Mobbar','state_id' => '8'],
        ['id' => '165','lga' => 'Monguno','state_id' => '8'],
        ['id' => '166','lga' => 'Ngala','state_id' => '8'],
        ['id' => '167','lga' => 'Nganzai','state_id' => '8'],
        ['id' => '168','lga' => 'Shani','state_id' => '8'],
        ['id' => '169','lga' => 'Abi','state_id' => '9'],
        ['id' => '170','lga' => 'Akamkpa','state_id' => '9'],
        ['id' => '171','lga' => 'Akpabuyo','state_id' => '9'],
        ['id' => '172','lga' => 'Bakassi','state_id' => '9'],
        ['id' => '173','lga' => 'Bekwarra','state_id' => '9'],
        ['id' => '174','lga' => 'Biase','state_id' => '9'],
        ['id' => '175','lga' => 'Boki','state_id' => '9'],
        ['id' => '176','lga' => 'Calabar Municipal','state_id' => '9'],
        ['id' => '177','lga' => 'Calabar South','state_id' => '9'],
        ['id' => '178','lga' => 'Etung','state_id' => '9'],
        ['id' => '179','lga' => 'Ikom','state_id' => '9'],
        ['id' => '180','lga' => 'Obanliku','state_id' => '9'],
        ['id' => '181','lga' => 'Obubra','state_id' => '9'],
        ['id' => '182','lga' => 'Obudu','state_id' => '9'],
        ['id' => '183','lga' => 'Odukpani','state_id' => '9'],
        ['id' => '184','lga' => 'Ogoja','state_id' => '9'],
        ['id' => '185','lga' => 'Yakuur','state_id' => '9'],
        ['id' => '186','lga' => 'Yala','state_id' => '9'],
        ['id' => '187','lga' => 'Aniocha North','state_id' => '10'],
        ['id' => '188','lga' => 'Aniocha South','state_id' => '10'],
        ['id' => '189','lga' => 'Bomadi','state_id' => '10'],
        ['id' => '190','lga' => 'Burutu','state_id' => '10'],
        ['id' => '191','lga' => 'Ethiope East','state_id' => '10'],
        ['id' => '192','lga' => 'Ethiope West','state_id' => '10'],
        ['id' => '193','lga' => 'Ika North East','state_id' => '10'],
        ['id' => '194','lga' => 'Ika South','state_id' => '10'],
        ['id' => '195','lga' => 'Isoko North','state_id' => '10'],
        ['id' => '196','lga' => 'Isoko South','state_id' => '10'],
        ['id' => '197','lga' => 'Ndokwa East','state_id' => '10'],
        ['id' => '198','lga' => 'Ndokwa West','state_id' => '10'],
        ['id' => '199','lga' => 'Okpe','state_id' => '10'],
        ['id' => '200','lga' => 'Oshimili North','state_id' => '10'],
        ['id' => '201','lga' => 'Oshimili South','state_id' => '10'],
        ['id' => '202','lga' => 'Patani','state_id' => '10'],
        ['id' => '203','lga' => 'Sapele','state_id' => '10'],
        ['id' => '204','lga' => 'Udu','state_id' => '10'],
        ['id' => '205','lga' => 'Ughelli North','state_id' => '10'],
        ['id' => '206','lga' => 'Ughelli South','state_id' => '10'],
        ['id' => '207','lga' => 'Ukwuani','state_id' => '10'],
        ['id' => '208','lga' => 'Uvwie','state_id' => '10'],
        ['id' => '209','lga' => 'Warri North','state_id' => '10'],
        ['id' => '210','lga' => 'Warri South','state_id' => '10'],
        ['id' => '211','lga' => 'Warri South West','state_id' => '10'],
        ['id' => '212','lga' => 'Abakaliki','state_id' => '11'],
        ['id' => '213','lga' => 'Afikpo North','state_id' => '11'],
        ['id' => '214','lga' => 'Afikpo South','state_id' => '11'],
        ['id' => '215','lga' => 'Ebonyi','state_id' => '11'],
        ['id' => '216','lga' => 'Ezza North','state_id' => '11'],
        ['id' => '217','lga' => 'Ezza South','state_id' => '11'],
        ['id' => '218','lga' => 'Ikwo','state_id' => '11'],
        ['id' => '219','lga' => 'Ishielu','state_id' => '11'],
        ['id' => '220','lga' => 'Ivo','state_id' => '11'],
        ['id' => '221','lga' => 'Izzi','state_id' => '11'],
        ['id' => '222','lga' => 'Ohaozara','state_id' => '11'],
        ['id' => '223','lga' => 'Ohaukwu','state_id' => '11'],
        ['id' => '224','lga' => 'Onicha','state_id' => '11'],
        ['id' => '225','lga' => 'Akoko-Edo','state_id' => '13'],
        ['id' => '226','lga' => 'Egor','state_id' => '13'],
        ['id' => '227','lga' => 'Esan Central','state_id' => '13'],
        ['id' => '228','lga' => 'Esan North-East','state_id' => '13'],
        ['id' => '229','lga' => 'Esan South-East','state_id' => '13'],
        ['id' => '230','lga' => 'Esan West','state_id' => '13'],
        ['id' => '231','lga' => 'Etsako Central','state_id' => '13'],
        ['id' => '232','lga' => 'Etsako East','state_id' => '13'],
        ['id' => '233','lga' => 'Etsako West','state_id' => '13'],
        ['id' => '234','lga' => 'Igueben','state_id' => '13'],
        ['id' => '235','lga' => 'Ikpoba Okha','state_id' => '13'],
        ['id' => '236','lga' => 'Oredo','state_id' => '13'],
        ['id' => '237','lga' => 'Orhionmwon','state_id' => '13'],
        ['id' => '238','lga' => 'Ovia North-East','state_id' => '13'],
        ['id' => '239','lga' => 'Ovia South-West','state_id' => '13'],
        ['id' => '240','lga' => 'Owan East','state_id' => '13'],
        ['id' => '241','lga' => 'Owan West','state_id' => '13'],
        ['id' => '242','lga' => 'Uhunmwonde','state_id' => '13'],
        ['id' => '243','lga' => 'Ado Ekiti','state_id' => '14'],
        ['id' => '244','lga' => 'Efon','state_id' => '14'],
        ['id' => '245','lga' => 'Ekiti East','state_id' => '14'],
        ['id' => '246','lga' => 'Ekiti South-West','state_id' => '14'],
        ['id' => '247','lga' => 'Ekiti West','state_id' => '14'],
        ['id' => '248','lga' => 'Emure','state_id' => '14'],
        ['id' => '249','lga' => 'Gbonyin','state_id' => '14'],
        ['id' => '250','lga' => 'Ido Osi','state_id' => '14'],
        ['id' => '251','lga' => 'Ijero','state_id' => '14'],
        ['id' => '252','lga' => 'Ikere','state_id' => '14'],
        ['id' => '253','lga' => 'Ikole','state_id' => '14'],
        ['id' => '254','lga' => 'Ilejemeje','state_id' => '14'],
        ['id' => '255','lga' => 'Irepodun/Ifelodun','state_id' => '14'],
        ['id' => '256','lga' => 'Ise/Orun','state_id' => '14'],
        ['id' => '257','lga' => 'Moba','state_id' => '14'],
        ['id' => '258','lga' => 'Oye','state_id' => '14'],
        ['id' => '259','lga' => 'Aninri','state_id' => '12'],
        ['id' => '260','lga' => 'Awgu','state_id' => '12'],
        ['id' => '261','lga' => 'Enugu East','state_id' => '12'],
        ['id' => '262','lga' => 'Enugu North','state_id' => '12'],
        ['id' => '263','lga' => 'Enugu South','state_id' => '12'],
        ['id' => '264','lga' => 'Ezeagu','state_id' => '12'],
        ['id' => '265','lga' => 'Igbo Etiti','state_id' => '12'],
        ['id' => '266','lga' => 'Igbo Eze North','state_id' => '12'],
        ['id' => '267','lga' => 'Igbo Eze South','state_id' => '12'],
        ['id' => '268','lga' => 'Isi Uzo','state_id' => '12'],
        ['id' => '269','lga' => 'Nkanu East','state_id' => '12'],
        ['id' => '270','lga' => 'Nkanu West','state_id' => '12'],
        ['id' => '271','lga' => 'Nsukka','state_id' => '12'],
        ['id' => '272','lga' => 'Oji River','state_id' => '12'],
        ['id' => '273','lga' => 'Udenu','state_id' => '12'],
        ['id' => '274','lga' => 'Udi','state_id' => '12'],
        ['id' => '275','lga' => 'Uzo Uwani','state_id' => '12'],
        ['id' => '276','lga' => 'Abaji','state_id' => '37'],
        ['id' => '277','lga' => 'Bwari','state_id' => '37'],
        ['id' => '278','lga' => 'Gwagwalada','state_id' => '37'],
        ['id' => '279','lga' => 'Kuje','state_id' => '37'],
        ['id' => '280','lga' => 'Kwali','state_id' => '37'],
        ['id' => '281','lga' => 'Municipal Area Council','state_id' => '37'],
        ['id' => '282','lga' => 'Akko','state_id' => '15'],
        ['id' => '283','lga' => 'Balanga','state_id' => '15'],
        ['id' => '284','lga' => 'Billiri','state_id' => '15'],
        ['id' => '285','lga' => 'Dukku','state_id' => '15'],
        ['id' => '286','lga' => 'Funakaye','state_id' => '15'],
        ['id' => '287','lga' => 'Gombe','state_id' => '15'],
        ['id' => '288','lga' => 'Kaltungo','state_id' => '15'],
        ['id' => '289','lga' => 'Kwami','state_id' => '15'],
        ['id' => '290','lga' => 'Nafada','state_id' => '15'],
        ['id' => '291','lga' => 'Shongom','state_id' => '15'],
        ['id' => '292','lga' => 'Yamaltu/Deba','state_id' => '15'],
        ['id' => '293','lga' => 'Aboh Mbaise','state_id' => '16'],
        ['id' => '294','lga' => 'Ahiazu Mbaise','state_id' => '16'],
        ['id' => '295','lga' => 'Ehime Mbano','state_id' => '16'],
        ['id' => '296','lga' => 'Ezinihitte','state_id' => '16'],
        ['id' => '297','lga' => 'Ideato North','state_id' => '16'],
        ['id' => '298','lga' => 'Ideato South','state_id' => '16'],
        ['id' => '299','lga' => 'Ihitte/Uboma','state_id' => '16'],
        ['id' => '300','lga' => 'Ikeduru','state_id' => '16'],
        ['id' => '301','lga' => 'Isiala Mbano','state_id' => '16'],
        ['id' => '302','lga' => 'Isu','state_id' => '16'],
        ['id' => '303','lga' => 'Mbaitoli','state_id' => '16'],
        ['id' => '304','lga' => 'Ngor Okpala','state_id' => '16'],
        ['id' => '305','lga' => 'Njaba','state_id' => '16'],
        ['id' => '306','lga' => 'Nkwerre','state_id' => '16'],
        ['id' => '307','lga' => 'Nwangele','state_id' => '16'],
        ['id' => '308','lga' => 'Obowo','state_id' => '16'],
        ['id' => '309','lga' => 'Oguta','state_id' => '16'],
        ['id' => '310','lga' => 'Ohaji/Egbema','state_id' => '16'],
        ['id' => '311','lga' => 'Okigwe','state_id' => '16'],
        ['id' => '312','lga' => 'Orlu','state_id' => '16'],
        ['id' => '313','lga' => 'Orsu','state_id' => '16'],
        ['id' => '314','lga' => 'Oru East','state_id' => '16'],
        ['id' => '315','lga' => 'Oru West','state_id' => '16'],
        ['id' => '316','lga' => 'Owerri Municipal','state_id' => '16'],
        ['id' => '317','lga' => 'Owerri North','state_id' => '16'],
        ['id' => '318','lga' => 'Owerri West','state_id' => '16'],
        ['id' => '319','lga' => 'Unuimo','state_id' => '16'],
        ['id' => '320','lga' => 'Auyo','state_id' => '17'],
        ['id' => '321','lga' => 'Babura','state_id' => '17'],
        ['id' => '322','lga' => 'Biriniwa','state_id' => '17'],
        ['id' => '323','lga' => 'Birnin Kudu','state_id' => '17'],
        ['id' => '324','lga' => 'Buji','state_id' => '17'],
        ['id' => '325','lga' => 'Dutse','state_id' => '17'],
        ['id' => '326','lga' => 'Gagarawa','state_id' => '17'],
        ['id' => '327','lga' => 'Garki','state_id' => '17'],
        ['id' => '328','lga' => 'Gumel','state_id' => '17'],
        ['id' => '329','lga' => 'Guri','state_id' => '17'],
        ['id' => '330','lga' => 'Gwaram','state_id' => '17'],
        ['id' => '331','lga' => 'Gwiwa','state_id' => '17'],
        ['id' => '332','lga' => 'Hadejia','state_id' => '17'],
        ['id' => '333','lga' => 'Jahun','state_id' => '17'],
        ['id' => '334','lga' => 'Kafin Hausa','state_id' => '17'],
        ['id' => '335','lga' => 'Kaugama','state_id' => '17'],
        ['id' => '336','lga' => 'Kazaure','state_id' => '17'],
        ['id' => '337','lga' => 'Kiri Kasama','state_id' => '17'],
        ['id' => '338','lga' => 'Kiyawa','state_id' => '17'],
        ['id' => '339','lga' => 'Maigatari','state_id' => '17'],
        ['id' => '340','lga' => 'Malam Madori','state_id' => '17'],
        ['id' => '341','lga' => 'Miga','state_id' => '17'],
        ['id' => '342','lga' => 'Ringim','state_id' => '17'],
        ['id' => '343','lga' => 'Roni','state_id' => '17'],
        ['id' => '344','lga' => 'Sule Tankarkar','state_id' => '17'],
        ['id' => '345','lga' => 'Taura','state_id' => '17'],
        ['id' => '346','lga' => 'Yankwashi','state_id' => '17'],
        ['id' => '347','lga' => 'Birnin Gwari','state_id' => '18'],
        ['id' => '348','lga' => 'Chikun','state_id' => '18'],
        ['id' => '349','lga' => 'Giwa','state_id' => '18'],
        ['id' => '350','lga' => 'Igabi','state_id' => '18'],
        ['id' => '351','lga' => 'Ikara','state_id' => '18'],
        ['id' => '352','lga' => 'Jaba','state_id' => '18'],
        ['id' => '353','lga' => 'Jema\'a','state_id' => '18'],
        ['id' => '354','lga' => 'Kachia','state_id' => '18'],
        ['id' => '355','lga' => 'Kaduna North','state_id' => '18'],
        ['id' => '356','lga' => 'Kaduna South','state_id' => '18'],
        ['id' => '357','lga' => 'Kagarko','state_id' => '18'],
        ['id' => '358','lga' => 'Kajuru','state_id' => '18'],
        ['id' => '359','lga' => 'Kaura','state_id' => '18'],
        ['id' => '360','lga' => 'Kauru','state_id' => '18'],
        ['id' => '361','lga' => 'Kubau','state_id' => '18'],
        ['id' => '362','lga' => 'Kudan','state_id' => '18'],
        ['id' => '363','lga' => 'Lere','state_id' => '18'],
        ['id' => '364','lga' => 'Makarfi','state_id' => '18'],
        ['id' => '365','lga' => 'Sabon Gari','state_id' => '18'],
        ['id' => '366','lga' => 'Sanga','state_id' => '18'],
        ['id' => '367','lga' => 'Soba','state_id' => '18'],
        ['id' => '368','lga' => 'Zangon Kataf','state_id' => '18'],
        ['id' => '369','lga' => 'Zaria','state_id' => '18'],
        ['id' => '370','lga' => 'Ajingi','state_id' => '19'],
        ['id' => '371','lga' => 'Albasu','state_id' => '19'],
        ['id' => '372','lga' => 'Bagwai','state_id' => '19'],
        ['id' => '373','lga' => 'Bebeji','state_id' => '19'],
        ['id' => '374','lga' => 'Bichi','state_id' => '19'],
        ['id' => '375','lga' => 'Bunkure','state_id' => '19'],
        ['id' => '376','lga' => 'Dala','state_id' => '19'],
        ['id' => '377','lga' => 'Dambatta','state_id' => '19'],
        ['id' => '378','lga' => 'Dawakin Kudu','state_id' => '19'],
        ['id' => '379','lga' => 'Dawakin Tofa','state_id' => '19'],
        ['id' => '380','lga' => 'Doguwa','state_id' => '19'],
        ['id' => '381','lga' => 'Fagge','state_id' => '19'],
        ['id' => '382','lga' => 'Gabasawa','state_id' => '19'],
        ['id' => '383','lga' => 'Garko','state_id' => '19'],
        ['id' => '384','lga' => 'Garun Mallam','state_id' => '19'],
        ['id' => '385','lga' => 'Gaya','state_id' => '19'],
        ['id' => '386','lga' => 'Gezawa','state_id' => '19'],
        ['id' => '387','lga' => 'Gwale','state_id' => '19'],
        ['id' => '388','lga' => 'Gwarzo','state_id' => '19'],
        ['id' => '389','lga' => 'Kabo','state_id' => '19'],
        ['id' => '390','lga' => 'Kano Municipal','state_id' => '19'],
        ['id' => '391','lga' => 'Karaye','state_id' => '19'],
        ['id' => '392','lga' => 'Kibiya','state_id' => '19'],
        ['id' => '393','lga' => 'Kiru','state_id' => '19'],
        ['id' => '394','lga' => 'Kumbotso','state_id' => '19'],
        ['id' => '395','lga' => 'Kunchi','state_id' => '19'],
        ['id' => '396','lga' => 'Kura','state_id' => '19'],
        ['id' => '397','lga' => 'Madobi','state_id' => '19'],
        ['id' => '398','lga' => 'Makoda','state_id' => '19'],
        ['id' => '399','lga' => 'Minjibir','state_id' => '19'],
        ['id' => '400','lga' => 'Nasarawa','state_id' => '19'],
        ['id' => '401','lga' => 'Rano','state_id' => '19'],
        ['id' => '402','lga' => 'Rimin Gado','state_id' => '19'],
        ['id' => '403','lga' => 'Rogo','state_id' => '19'],
        ['id' => '404','lga' => 'Shanono','state_id' => '19'],
        ['id' => '405','lga' => 'Sumaila','state_id' => '19'],
        ['id' => '406','lga' => 'Takai','state_id' => '19'],
        ['id' => '407','lga' => 'Tarauni','state_id' => '19'],
        ['id' => '408','lga' => 'Tofa','state_id' => '19'],
        ['id' => '409','lga' => 'Tsanyawa','state_id' => '19'],
        ['id' => '410','lga' => 'Tudun Wada','state_id' => '19'],
        ['id' => '411','lga' => 'Ungogo','state_id' => '19'],
        ['id' => '412','lga' => 'Warawa','state_id' => '19'],
        ['id' => '413','lga' => 'Wudil','state_id' => '19'],
        ['id' => '414','lga' => 'Bakori','state_id' => '20'],
        ['id' => '415','lga' => 'Batagarawa','state_id' => '20'],
        ['id' => '416','lga' => 'Batsari','state_id' => '20'],
        ['id' => '417','lga' => 'Baure','state_id' => '20'],
        ['id' => '418','lga' => 'Bindawa','state_id' => '20'],
        ['id' => '419','lga' => 'Charanchi','state_id' => '20'],
        ['id' => '420','lga' => 'Dan Musa','state_id' => '20'],
        ['id' => '421','lga' => 'Dandume','state_id' => '20'],
        ['id' => '422','lga' => 'Danja','state_id' => '20'],
        ['id' => '423','lga' => 'Daura','state_id' => '20'],
        ['id' => '424','lga' => 'Dutsi','state_id' => '20'],
        ['id' => '425','lga' => 'Dutsin Ma','state_id' => '20'],
        ['id' => '426','lga' => 'Faskari','state_id' => '20'],
        ['id' => '427','lga' => 'Funtua','state_id' => '20'],
        ['id' => '428','lga' => 'Ingawa','state_id' => '20'],
        ['id' => '429','lga' => 'Jibia','state_id' => '20'],
        ['id' => '430','lga' => 'Kafur','state_id' => '20'],
        ['id' => '431','lga' => 'Kaita','state_id' => '20'],
        ['id' => '432','lga' => 'Kankara','state_id' => '20'],
        ['id' => '433','lga' => 'Kankia','state_id' => '20'],
        ['id' => '434','lga' => 'Katsina','state_id' => '20'],
        ['id' => '435','lga' => 'Kurfi','state_id' => '20'],
        ['id' => '436','lga' => 'Kusada','state_id' => '20'],
        ['id' => '437','lga' => 'Mai\'Adua','state_id' => '20'],
        ['id' => '438','lga' => 'Malumfashi','state_id' => '20'],
        ['id' => '439','lga' => 'Mani','state_id' => '20'],
        ['id' => '440','lga' => 'Mashi','state_id' => '20'],
        ['id' => '441','lga' => 'Matazu','state_id' => '20'],
        ['id' => '442','lga' => 'Musawa','state_id' => '20'],
        ['id' => '443','lga' => 'Rimi','state_id' => '20'],
        ['id' => '444','lga' => 'Sabuwa','state_id' => '20'],
        ['id' => '445','lga' => 'Safana','state_id' => '20'],
        ['id' => '446','lga' => 'Sandamu','state_id' => '20'],
        ['id' => '447','lga' => 'Zango','state_id' => '20'],
        ['id' => '448','lga' => 'Aleiro','state_id' => '21'],
        ['id' => '449','lga' => 'Arewa Dandi','state_id' => '21'],
        ['id' => '450','lga' => 'Argungu','state_id' => '21'],
        ['id' => '451','lga' => 'Augie','state_id' => '21'],
        ['id' => '452','lga' => 'Bagudo','state_id' => '21'],
        ['id' => '453','lga' => 'Birnin Kebbi','state_id' => '21'],
        ['id' => '454','lga' => 'Bunza','state_id' => '21'],
        ['id' => '455','lga' => 'Dandi','state_id' => '21'],
        ['id' => '456','lga' => 'Fakai','state_id' => '21'],
        ['id' => '457','lga' => 'Gwandu','state_id' => '21'],
        ['id' => '458','lga' => 'Jega','state_id' => '21'],
        ['id' => '459','lga' => 'Kalgo','state_id' => '21'],
        ['id' => '460','lga' => 'Koko/Besse','state_id' => '21'],
        ['id' => '461','lga' => 'Maiyama','state_id' => '21'],
        ['id' => '462','lga' => 'Ngaski','state_id' => '21'],
        ['id' => '463','lga' => 'Sakaba','state_id' => '21'],
        ['id' => '464','lga' => 'Shanga','state_id' => '21'],
        ['id' => '465','lga' => 'Suru','state_id' => '21'],
        ['id' => '466','lga' => 'Wasagu/Danko','state_id' => '21'],
        ['id' => '467','lga' => 'Yauri','state_id' => '21'],
        ['id' => '468','lga' => 'Zuru','state_id' => '21'],
        ['id' => '469','lga' => 'Adavi','state_id' => '22'],
        ['id' => '470','lga' => 'Ajaokuta','state_id' => '22'],
        ['id' => '471','lga' => 'Ankpa','state_id' => '22'],
        ['id' => '472','lga' => 'Bassa','state_id' => '22'],
        ['id' => '473','lga' => 'Dekina','state_id' => '22'],
        ['id' => '474','lga' => 'Ibaji','state_id' => '22'],
        ['id' => '475','lga' => 'Idah','state_id' => '22'],
        ['id' => '476','lga' => 'Igalamela Odolu','state_id' => '22'],
        ['id' => '477','lga' => 'Ijumu','state_id' => '22'],
        ['id' => '478','lga' => 'Kabba/Bunu','state_id' => '22'],
        ['id' => '479','lga' => 'Kogi','state_id' => '22'],
        ['id' => '480','lga' => 'Lokoja','state_id' => '22'],
        ['id' => '481','lga' => 'Mopa Muro','state_id' => '22'],
        ['id' => '482','lga' => 'Ofu','state_id' => '22'],
        ['id' => '483','lga' => 'Ogori/Magongo','state_id' => '22'],
        ['id' => '484','lga' => 'Okehi','state_id' => '22'],
        ['id' => '485','lga' => 'Okene','state_id' => '22'],
        ['id' => '486','lga' => 'Olamaboro','state_id' => '22'],
        ['id' => '487','lga' => 'Omala','state_id' => '22'],
        ['id' => '488','lga' => 'Yagba East','state_id' => '22'],
        ['id' => '489','lga' => 'Yagba West','state_id' => '22'],
        ['id' => '490','lga' => 'Asa','state_id' => '23'],
        ['id' => '491','lga' => 'Baruten','state_id' => '23'],
        ['id' => '492','lga' => 'Edu','state_id' => '23'],
        ['id' => '493','lga' => 'Ekiti','state_id' => '23'],
        ['id' => '494','lga' => 'Ifelodun','state_id' => '23'],
        ['id' => '495','lga' => 'Ilorin East','state_id' => '23'],
        ['id' => '496','lga' => 'Ilorin South','state_id' => '23'],
        ['id' => '497','lga' => 'Ilorin West','state_id' => '23'],
        ['id' => '498','lga' => 'Irepodun','state_id' => '23'],
        ['id' => '499','lga' => 'Isin','state_id' => '23'],
        ['id' => '500','lga' => 'Kaiama','state_id' => '23'],
        ['id' => '501','lga' => 'Moro','state_id' => '23'],
        ['id' => '502','lga' => 'Offa','state_id' => '23'],
        ['id' => '503','lga' => 'Oke Ero','state_id' => '23'],
        ['id' => '504','lga' => 'Oyun','state_id' => '23'],
        ['id' => '505','lga' => 'Pategi','state_id' => '23'],
        ['id' => '506','lga' => 'Agege','state_id' => '24'],
        ['id' => '507','lga' => 'Ajeromi-Ifelodun','state_id' => '24'],
        ['id' => '508','lga' => 'Alimosho','state_id' => '24'],
        ['id' => '509','lga' => 'Amuwo-Odofin','state_id' => '24'],
        ['id' => '510','lga' => 'Apapa','state_id' => '24'],
        ['id' => '511','lga' => 'Badagry','state_id' => '24'],
        ['id' => '512','lga' => 'Epe','state_id' => '24'],
        ['id' => '513','lga' => 'Eti Osa','state_id' => '24'],
        ['id' => '514','lga' => 'Ibeju-Lekki','state_id' => '24'],
        ['id' => '515','lga' => 'Ifako-Ijaiye','state_id' => '24'],
        ['id' => '516','lga' => 'Ikeja','state_id' => '24'],
        ['id' => '517','lga' => 'Ikorodu','state_id' => '24'],
        ['id' => '518','lga' => 'Kosofe','state_id' => '24'],
        ['id' => '519','lga' => 'Lagos Island','state_id' => '24'],
        ['id' => '520','lga' => 'Lagos Mainland','state_id' => '24'],
        ['id' => '521','lga' => 'Mushin','state_id' => '24'],
        ['id' => '522','lga' => 'Ojo','state_id' => '24'],
        ['id' => '523','lga' => 'Oshodi-Isolo','state_id' => '24'],
        ['id' => '524','lga' => 'Shomolu','state_id' => '24'],
        ['id' => '525','lga' => 'Surulere','state_id' => '24'],
        ['id' => '526','lga' => 'Akwanga','state_id' => '25'],
        ['id' => '527','lga' => 'Awe','state_id' => '25'],
        ['id' => '528','lga' => 'Doma','state_id' => '25'],
        ['id' => '529','lga' => 'Karu','state_id' => '25'],
        ['id' => '530','lga' => 'Keana','state_id' => '25'],
        ['id' => '531','lga' => 'Keffi','state_id' => '25'],
        ['id' => '532','lga' => 'Kokona','state_id' => '25'],
        ['id' => '533','lga' => 'Lafia','state_id' => '25'],
        ['id' => '534','lga' => 'Nasarawa','state_id' => '25'],
        ['id' => '535','lga' => 'Nasarawa Egon','state_id' => '25'],
        ['id' => '536','lga' => 'Obi','state_id' => '25'],
        ['id' => '537','lga' => 'Toto','state_id' => '25'],
        ['id' => '538','lga' => 'Wamba','state_id' => '25'],
        ['id' => '539','lga' => 'Agaie','state_id' => '26'],
        ['id' => '540','lga' => 'Agwara','state_id' => '26'],
        ['id' => '541','lga' => 'Bida','state_id' => '26'],
        ['id' => '542','lga' => 'Borgu','state_id' => '26'],
        ['id' => '543','lga' => 'Bosso','state_id' => '26'],
        ['id' => '544','lga' => 'Chanchaga','state_id' => '26'],
        ['id' => '545','lga' => 'Edati','state_id' => '26'],
        ['id' => '546','lga' => 'Gbako','state_id' => '26'],
        ['id' => '547','lga' => 'Gurara','state_id' => '26'],
        ['id' => '548','lga' => 'Katcha','state_id' => '26'],
        ['id' => '549','lga' => 'Kontagora','state_id' => '26'],
        ['id' => '550','lga' => 'Lapai','state_id' => '26'],
        ['id' => '551','lga' => 'Lavun','state_id' => '26'],
        ['id' => '552','lga' => 'Magama','state_id' => '26'],
        ['id' => '553','lga' => 'Mariga','state_id' => '26'],
        ['id' => '554','lga' => 'Mashegu','state_id' => '26'],
        ['id' => '555','lga' => 'Mokwa','state_id' => '26'],
        ['id' => '556','lga' => 'Moya','state_id' => '26'],
        ['id' => '557','lga' => 'Paikoro','state_id' => '26'],
        ['id' => '558','lga' => 'Rafi','state_id' => '26'],
        ['id' => '559','lga' => 'Rijau','state_id' => '26'],
        ['id' => '560','lga' => 'Shiroro','state_id' => '26'],
        ['id' => '561','lga' => 'Suleja','state_id' => '26'],
        ['id' => '562','lga' => 'Tafa','state_id' => '26'],
        ['id' => '563','lga' => 'Wushishi','state_id' => '26'],
        ['id' => '564','lga' => 'Abeokuta North','state_id' => '27'],
        ['id' => '565','lga' => 'Abeokuta South','state_id' => '27'],
        ['id' => '566','lga' => 'Ado-Odo/Ota','state_id' => '27'],
        ['id' => '567','lga' => 'Egbado North','state_id' => '27'],
        ['id' => '568','lga' => 'Egbado South','state_id' => '27'],
        ['id' => '569','lga' => 'Ewekoro','state_id' => '27'],
        ['id' => '570','lga' => 'Ifo','state_id' => '27'],
        ['id' => '571','lga' => 'Ijebu East','state_id' => '27'],
        ['id' => '572','lga' => 'Ijebu North','state_id' => '27'],
        ['id' => '573','lga' => 'Ijebu North East','state_id' => '27'],
        ['id' => '574','lga' => 'Ijebu Ode','state_id' => '27'],
        ['id' => '575','lga' => 'Ikenne','state_id' => '27'],
        ['id' => '576','lga' => 'Imeko Afon','state_id' => '27'],
        ['id' => '577','lga' => 'Ipokia','state_id' => '27'],
        ['id' => '578','lga' => 'Obafemi Owode','state_id' => '27'],
        ['id' => '579','lga' => 'Odeda','state_id' => '27'],
        ['id' => '580','lga' => 'Odogbolu','state_id' => '27'],
        ['id' => '581','lga' => 'Ogun Waterside','state_id' => '27'],
        ['id' => '582','lga' => 'Remo North','state_id' => '27'],
        ['id' => '583','lga' => 'Shagamu','state_id' => '27'],
        ['id' => '584','lga' => 'Akoko North-East','state_id' => '28'],
        ['id' => '585','lga' => 'Akoko North-West','state_id' => '28'],
        ['id' => '586','lga' => 'Akoko South-East','state_id' => '28'],
        ['id' => '587','lga' => 'Akoko South-West','state_id' => '28'],
        ['id' => '588','lga' => 'Akure North','state_id' => '28'],
        ['id' => '589','lga' => 'Akure South','state_id' => '28'],
        ['id' => '590','lga' => 'Ese Odo','state_id' => '28'],
        ['id' => '591','lga' => 'Idanre','state_id' => '28'],
        ['id' => '592','lga' => 'Ifedore','state_id' => '28'],
        ['id' => '593','lga' => 'Ilaje','state_id' => '28'],
        ['id' => '594','lga' => 'Ile Oluji/Okeigbo','state_id' => '28'],
        ['id' => '595','lga' => 'Irele','state_id' => '28'],
        ['id' => '596','lga' => 'Odigbo','state_id' => '28'],
        ['id' => '597','lga' => 'Okitipupa','state_id' => '28'],
        ['id' => '598','lga' => 'Ondo East','state_id' => '28'],
        ['id' => '599','lga' => 'Ondo West','state_id' => '28'],
        ['id' => '600','lga' => 'Ose','state_id' => '28'],
        ['id' => '601','lga' => 'Owo','state_id' => '28'],
        ['id' => '602','lga' => 'Aiyedaade','state_id' => '29'],
        ['id' => '603','lga' => 'Aiyedire','state_id' => '29'],
        ['id' => '604','lga' => 'Atakunmosa East','state_id' => '29'],
        ['id' => '605','lga' => 'Atakunmosa West','state_id' => '29'],
        ['id' => '606','lga' => 'Boluwaduro','state_id' => '29'],
        ['id' => '607','lga' => 'Boripe','state_id' => '29'],
        ['id' => '608','lga' => 'Ede North','state_id' => '29'],
        ['id' => '609','lga' => 'Ede South','state_id' => '29'],
        ['id' => '610','lga' => 'Egbedore','state_id' => '29'],
        ['id' => '611','lga' => 'Ejigbo','state_id' => '29'],
        ['id' => '612','lga' => 'Ife Central','state_id' => '29'],
        ['id' => '613','lga' => 'Ife East','state_id' => '29'],
        ['id' => '614','lga' => 'Ife North','state_id' => '29'],
        ['id' => '615','lga' => 'Ife South','state_id' => '29'],
        ['id' => '616','lga' => 'Ifedayo','state_id' => '29'],
        ['id' => '617','lga' => 'Ifelodun','state_id' => '29'],
        ['id' => '618','lga' => 'Ila','state_id' => '29'],
        ['id' => '619','lga' => 'Ilesa East','state_id' => '29'],
        ['id' => '620','lga' => 'Ilesa West','state_id' => '29'],
        ['id' => '621','lga' => 'Irepodun','state_id' => '29'],
        ['id' => '622','lga' => 'Irewole','state_id' => '29'],
        ['id' => '623','lga' => 'Isokan','state_id' => '29'],
        ['id' => '624','lga' => 'Iwo','state_id' => '29'],
        ['id' => '625','lga' => 'Obokun','state_id' => '29'],
        ['id' => '626','lga' => 'Odo Otin','state_id' => '29'],
        ['id' => '627','lga' => 'Ola Oluwa','state_id' => '29'],
        ['id' => '628','lga' => 'Olorunda','state_id' => '29'],
        ['id' => '629','lga' => 'Oriade','state_id' => '29'],
        ['id' => '630','lga' => 'Orolu','state_id' => '29'],
        ['id' => '631','lga' => 'Osogbo','state_id' => '29'],
        ['id' => '632','lga' => 'Afijio','state_id' => '30'],
        ['id' => '633','lga' => 'Akinyele','state_id' => '30'],
        ['id' => '634','lga' => 'Atiba','state_id' => '30'],
        ['id' => '635','lga' => 'Atisbo','state_id' => '30'],
        ['id' => '636','lga' => 'Egbeda','state_id' => '30'],
        ['id' => '637','lga' => 'Ibadan North','state_id' => '30'],
        ['id' => '638','lga' => 'Ibadan North-East','state_id' => '30'],
        ['id' => '639','lga' => 'Ibadan North-West','state_id' => '30'],
        ['id' => '640','lga' => 'Ibadan South-East','state_id' => '30'],
        ['id' => '641','lga' => 'Ibadan South-West','state_id' => '30'],
        ['id' => '642','lga' => 'Ibarapa Central','state_id' => '30'],
        ['id' => '643','lga' => 'Ibarapa East','state_id' => '30'],
        ['id' => '644','lga' => 'Ibarapa North','state_id' => '30'],
        ['id' => '645','lga' => 'Ido','state_id' => '30'],
        ['id' => '646','lga' => 'Irepo','state_id' => '30'],
        ['id' => '647','lga' => 'Iseyin','state_id' => '30'],
        ['id' => '648','lga' => 'Itesiwaju','state_id' => '30'],
        ['id' => '649','lga' => 'Iwajowa','state_id' => '30'],
        ['id' => '650','lga' => 'Kajola','state_id' => '30'],
        ['id' => '651','lga' => 'Lagelu','state_id' => '30'],
        ['id' => '652','lga' => 'Ogbomosho North','state_id' => '30'],
        ['id' => '653','lga' => 'Ogbomosho South','state_id' => '30'],
        ['id' => '654','lga' => 'Ogo Oluwa','state_id' => '30'],
        ['id' => '655','lga' => 'Olorunsogo','state_id' => '30'],
        ['id' => '656','lga' => 'Oluyole','state_id' => '30'],
        ['id' => '657','lga' => 'Ona Ara','state_id' => '30'],
        ['id' => '658','lga' => 'Orelope','state_id' => '30'],
        ['id' => '659','lga' => 'Ori Ire','state_id' => '30'],
        ['id' => '660','lga' => 'Oyo','state_id' => '30'],
        ['id' => '661','lga' => 'Oyo East','state_id' => '30'],
        ['id' => '662','lga' => 'Saki East','state_id' => '30'],
        ['id' => '663','lga' => 'Saki West','state_id' => '30'],
        ['id' => '664','lga' => 'Surulere','state_id' => '30'],
        ['id' => '665','lga' => 'Barkin Ladi','state_id' => '31'],
        ['id' => '666','lga' => 'Bassa','state_id' => '31'],
        ['id' => '667','lga' => 'Bokkos','state_id' => '31'],
        ['id' => '668','lga' => 'Jos East','state_id' => '31'],
        ['id' => '669','lga' => 'Jos North','state_id' => '31'],
        ['id' => '670','lga' => 'Jos South','state_id' => '31'],
        ['id' => '671','lga' => 'Kanam','state_id' => '31'],
        ['id' => '672','lga' => 'Kanke','state_id' => '31'],
        ['id' => '673','lga' => 'Langtang North','state_id' => '31'],
        ['id' => '674','lga' => 'Langtang South','state_id' => '31'],
        ['id' => '675','lga' => 'Mangu','state_id' => '31'],
        ['id' => '676','lga' => 'Mikang','state_id' => '31'],
        ['id' => '677','lga' => 'Pankshin','state_id' => '31'],
        ['id' => '678','lga' => 'Qua\'an Pan','state_id' => '31'],
        ['id' => '679','lga' => 'Riyom','state_id' => '31'],
        ['id' => '680','lga' => 'Shendam','state_id' => '31'],
        ['id' => '681','lga' => 'Wase','state_id' => '31'],
        ['id' => '682','lga' => 'Abua/Odual','state_id' => '32'],
        ['id' => '683','lga' => 'Ahoada East','state_id' => '32'],
        ['id' => '684','lga' => 'Ahoada West','state_id' => '32'],
        ['id' => '685','lga' => 'Akuku-Toru','state_id' => '32'],
        ['id' => '686','lga' => 'Andoni','state_id' => '32'],
        ['id' => '687','lga' => 'Asari-Toru','state_id' => '32'],
        ['id' => '688','lga' => 'Bonny','state_id' => '32'],
        ['id' => '689','lga' => 'Degema','state_id' => '32'],
        ['id' => '690','lga' => 'Eleme','state_id' => '32'],
        ['id' => '691','lga' => 'Emuoha','state_id' => '32'],
        ['id' => '692','lga' => 'Etche','state_id' => '32'],
        ['id' => '693','lga' => 'Gokana','state_id' => '32'],
        ['id' => '694','lga' => 'Ikwerre','state_id' => '32'],
        ['id' => '695','lga' => 'Khana','state_id' => '32'],
        ['id' => '696','lga' => 'Obio/Akpor','state_id' => '32'],
        ['id' => '697','lga' => 'Ogba/Egbema/Ndoni','state_id' => '32'],
        ['id' => '698','lga' => 'Ogu/Bolo','state_id' => '32'],
        ['id' => '699','lga' => 'Okrika','state_id' => '32'],
        ['id' => '700','lga' => 'Omuma','state_id' => '32'],
        ['id' => '701','lga' => 'Opobo/Nkoro','state_id' => '32'],
        ['id' => '702','lga' => 'Oyigbo','state_id' => '32'],
        ['id' => '703','lga' => 'Port Harcourt','state_id' => '32'],
        ['id' => '704','lga' => 'Tai','state_id' => '32'],
        ['id' => '705','lga' => 'Binji','state_id' => '33'],
        ['id' => '706','lga' => 'Bodinga','state_id' => '33'],
        ['id' => '707','lga' => 'Dange Shuni','state_id' => '33'],
        ['id' => '708','lga' => 'Gada','state_id' => '33'],
        ['id' => '709','lga' => 'Goronyo','state_id' => '33'],
        ['id' => '710','lga' => 'Gudu','state_id' => '33'],
        ['id' => '711','lga' => 'Gwadabawa','state_id' => '33'],
        ['id' => '712','lga' => 'Illela','state_id' => '33'],
        ['id' => '713','lga' => 'Isa','state_id' => '33'],
        ['id' => '714','lga' => 'Kebbe','state_id' => '33'],
        ['id' => '715','lga' => 'Kware','state_id' => '33'],
        ['id' => '716','lga' => 'Rabah','state_id' => '33'],
        ['id' => '717','lga' => 'Sabon Birni','state_id' => '33'],
        ['id' => '718','lga' => 'Shagari','state_id' => '33'],
        ['id' => '719','lga' => 'Silame','state_id' => '33'],
        ['id' => '720','lga' => 'Sokoto North','state_id' => '33'],
        ['id' => '721','lga' => 'Sokoto South','state_id' => '33'],
        ['id' => '722','lga' => 'Tambuwal','state_id' => '33'],
        ['id' => '723','lga' => 'Tangaza','state_id' => '33'],
        ['id' => '724','lga' => 'Tureta','state_id' => '33'],
        ['id' => '725','lga' => 'Wamako','state_id' => '33'],
        ['id' => '726','lga' => 'Wurno','state_id' => '33'],
        ['id' => '727','lga' => 'Yabo','state_id' => '33'],
        ['id' => '728','lga' => 'Ardo Kola','state_id' => '34'],
        ['id' => '729','lga' => 'Bali','state_id' => '34'],
        ['id' => '730','lga' => 'Donga','state_id' => '34'],
        ['id' => '731','lga' => 'Gashaka','state_id' => '34'],
        ['id' => '732','lga' => 'Gassol','state_id' => '34'],
        ['id' => '733','lga' => 'Ibi','state_id' => '34'],
        ['id' => '734','lga' => 'Jalingo','state_id' => '34'],
        ['id' => '735','lga' => 'Karim Lamido','state_id' => '34'],
        ['id' => '736','lga' => 'Kumi','state_id' => '34'],
        ['id' => '737','lga' => 'Lau','state_id' => '34'],
        ['id' => '738','lga' => 'Sardauna','state_id' => '34'],
        ['id' => '739','lga' => 'Takum','state_id' => '34'],
        ['id' => '740','lga' => 'Ussa','state_id' => '34'],
        ['id' => '741','lga' => 'Wukari','state_id' => '34'],
        ['id' => '742','lga' => 'Yorro','state_id' => '34'],
        ['id' => '743','lga' => 'Zing','state_id' => '34'],
        ['id' => '744','lga' => 'Bade','state_id' => '35'],
        ['id' => '745','lga' => 'Bursari','state_id' => '35'],
        ['id' => '746','lga' => 'Damaturu','state_id' => '35'],
        ['id' => '747','lga' => 'Fika','state_id' => '35'],
        ['id' => '748','lga' => 'Fune','state_id' => '35'],
        ['id' => '749','lga' => 'Geidam','state_id' => '35'],
        ['id' => '750','lga' => 'Gujba','state_id' => '35'],
        ['id' => '751','lga' => 'Gulani','state_id' => '35'],
        ['id' => '752','lga' => 'Jakusko','state_id' => '35'],
        ['id' => '753','lga' => 'Karasuwa','state_id' => '35'],
        ['id' => '754','lga' => 'Machina','state_id' => '35'],
        ['id' => '755','lga' => 'Nangere','state_id' => '35'],
        ['id' => '756','lga' => 'Nguru','state_id' => '35'],
        ['id' => '757','lga' => 'Potiskum','state_id' => '35'],
        ['id' => '758','lga' => 'Tarmuwa','state_id' => '35'],
        ['id' => '759','lga' => 'Yunusari','state_id' => '35'],
        ['id' => '760','lga' => 'Yusufari','state_id' => '35'],
        ['id' => '761','lga' => 'Anka','state_id' => '36'],
        ['id' => '762','lga' => 'Bakura','state_id' => '36'],
        ['id' => '763','lga' => 'Birnin Magaji/Kiyaw','state_id' => '36'],
        ['id' => '764','lga' => 'Bukkuyum','state_id' => '36'],
        ['id' => '765','lga' => 'Bungudu','state_id' => '36'],
        ['id' => '766','lga' => 'Chafe','state_id' => '36'],
        ['id' => '767','lga' => 'Gummi','state_id' => '36'],
        ['id' => '768','lga' => 'Gusau','state_id' => '36'],
        ['id' => '769','lga' => 'Kaura Namoda','state_id' => '36'],
        ['id' => '770','lga' => 'Maradun','state_id' => '36'],
        ['id' => '771','lga' => 'Maru','state_id' => '36'],
        ['id' => '772','lga' => 'Shinkafi','state_id' => '36'],
        ['id' => '773','lga' => 'Talata Mafara','state_id' => '36'],
        ['id' => '774','lga' => 'Zurmi','state_id' => '36'],
        ['id' => '775','lga' => '','state_id' => '']
      ];
      
}
